import { ProjectStore, timelineAt } from './project.js';
import { MediaLibrary } from './media.js';
import { PreviewController } from './preview.js';
import { TimelineView } from './timeline.js';
import { saveProject,parseProject,relinkState } from './persistence.js';
import { BrowserExporter } from './exporter.js';
import { formatTime,download } from './utils.js';
const $=s=>document.querySelector(s),store=new ProjectStore(),library=new MediaLibrary();
const preview=new PreviewController($('#preview'),$('#music-preview'),store,library);let selected=null,toastTimer;
const timeline=new TimelineView({timeline:$('#timeline'),videoTrack:$('#video-track'),audioTrack:$('#audio-track'),ruler:$('#ruler'),playhead:$('#playhead')},store,{seek:t=>preview.seek(t),select:id=>{selected=id;updateButtons()},reorder:(a,b)=>store.reorder(a,b),trim:(id,e,v)=>store.trim(id,e,v),audioStart:v=>store.updateAudio({start:v}),audioTrim:(edge,value)=>store.updateAudio({[edge==='start'?'in':'out']:value})});
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='toast',3500)}
function updateButtons(){const has=!!store.state.clips.length,clip=store.state.clips.find(c=>c.id===selected);$('#undo').disabled=!store.undoStack.length;$('#redo').disabled=!store.redoStack.length;$('#delete-clip').disabled=!clip;$('#split').disabled=!clip;$('#play').disabled=!has;$('#duration').textContent=formatTime(store.duration);$('#video-volume').value=store.state.videoVolume;$('#video-mute').checked=store.state.videoMuted;$('#music-volume').value=store.state.musicVolume;$('#music-mute').checked=store.state.musicMuted;const editor=$('#clip-editor');editor.hidden=!clip;if(clip){$('#selected-name').textContent=clip.name;$('#selected-length').textContent=`${formatTime((clip.out-clip.in)/(clip.speed||1))} on timeline`;$('#trim-start-input').value=clip.in.toFixed(1);$('#trim-start-input').max=(clip.out-.1).toFixed(1);$('#trim-end-input').value=clip.out.toFixed(1);$('#trim-end-input').max=clip.sourceDuration;$('#clip-speed').value=String(clip.speed||1)}const empty=!has;$('#empty-preview').hidden=!empty;$('#preview').style.display=empty?'none':'block';timeline.render();preview.syncVolumes()}
store.addEventListener('change',()=>{if(selected&&!store.state.clips.some(c=>c.id===selected))selected=null;preview.time=Math.min(preview.time,store.duration);updateButtons()});preview.addEventListener('time',e=>{$('#current-time').textContent=formatTime(e.detail);$('#play').textContent=preview.playing?'❚❚':'▶';timeline.setTime(e.detail)});
async function importFiles(files,autoAdd=true){const {added,errors}=await library.addFiles(files);for(const asset of added)if(autoAdd){if(asset.type.startsWith('video/'))store.addVideo(asset);else if(!store.state.audio)store.setAudio(asset);else toast('Only one added audio track is supported.',true)}if(errors.length)toast(errors[0],true);else if(added.length)toast(`Added ${added.length} file${added.length===1?'':'s'}.`);renderMedia();return added}
function renderMedia(){const list=$('#media-list');list.replaceChildren();for(const a of library.assets.values()){const el=document.createElement('div');el.className='media-item';el.innerHTML=`<div class="media-thumb">${a.type.startsWith('video/')?'▶':'♫'}</div><div class="media-meta"><div class="media-name"></div><div class="media-duration">${formatTime(a.duration)}</div></div>`;el.querySelector('.media-name').textContent=a.name;el.title=a.type.startsWith('video/')?'Click to add another copy to the timeline':'Click to use as the music track';el.onclick=()=>a.type.startsWith('video/')?store.addVideo(a):store.setAudio(a);list.append(el)}}
const choose=()=>$('#media-input').click();$('#choose-files').onclick=$('#import-media').onclick=$('#empty-choose').onclick=choose;$('#media-input').onchange=e=>{importFiles(e.target.files);e.target.value=''};
$('#play').onclick=()=>preview.toggle();$('#rewind').onclick=()=>preview.seek(0,false);$('#split').onclick=()=>{if(!selected)return;const hit=timelineAt(store.state,preview.time);if(!hit||hit.clip.id!==selected)return toast('Move the playhead inside the selected clip first.',true);store.split(selected,hit.local-hit.clip.in)};$('#delete-clip').onclick=()=>{if(selected)store.deleteClip(selected)};
$('#trim-start-input').onchange=e=>selected&&store.trim(selected,'start',Number(e.target.value));$('#trim-end-input').onchange=e=>selected&&store.trim(selected,'end',Number(e.target.value));$('#clip-speed').onchange=e=>{if(selected){store.updateClip(selected,{speed:Number(e.target.value)});preview.seek(preview.time,false)}};function rotate(by){if(!selected)return;const c=store.state.clips.find(x=>x.id===selected);store.updateClip(selected,{rotation:((c.rotation||0)+by+360)%360});preview.seek(preview.time,false)}$('#rotate-left').onclick=()=>rotate(-90);$('#rotate-right').onclick=()=>rotate(90);
$('#undo').onclick=()=>store.undo();$('#redo').onclick=()=>store.redo();$('#new-project').onclick=()=>{if(store.state.clips.length&&!confirm('Start a new project? Unsaved edits will be lost.'))return;preview.pause();library.clear();store.reset();selected=null;renderMedia()};$('#save-project').onclick=()=>saveProject(store);$('#open-project').onclick=()=>$('#project-input').click();
$('#project-input').onchange=async e=>{try{const state=await parseProject(e.target.files[0]);const missing=relinkState(state,library);store.replace(state);if(missing.length)showRelink(missing);else toast('Project opened.')}catch(err){toast(err.message,true)}e.target.value=''};
function showRelink(names){const ul=$('#missing-list');ul.replaceChildren(...names.map(n=>{const li=document.createElement('li');li.textContent=n;return li}));$('#relink-dialog').showModal()}$('#relink-files').onclick=()=>$('#relink-input').click();$('#relink-input').onchange=async e=>{await importFiles(e.target.files,false);const state=structuredClone(store.state),missing=relinkState(state,library);store.replace(state,false);if(missing.length)showRelink(missing);else{$('#relink-dialog').close();toast('All media reconnected.')}};
for(const [id,key] of [['video-volume','videoVolume'],['video-mute','videoMuted'],['music-volume','musicVolume'],['music-mute','musicMuted']])$("#"+id).onchange=e=>store.settings({[key]:e.target.type==='checkbox'?e.target.checked:Number(e.target.value)});
window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.code==='Space'){e.preventDefault();preview.toggle()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?store.redo():store.undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();store.redo()}if((e.key==='Delete'||e.key==='Backspace')&&selected)store.deleteClip(selected)});
let dragDepth=0;window.addEventListener('dragenter',e=>{if(e.dataTransfer?.types.includes('Files')){dragDepth++;$('#drop-overlay').classList.add('visible')}});window.addEventListener('dragleave',()=>{if(--dragDepth<=0){dragDepth=0;$('#drop-overlay').classList.remove('visible')}});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('#drop-overlay').classList.remove('visible');importFiles(e.dataTransfer.files)});
const exporter=new BrowserExporter(store,library);$('#export-open').onclick=()=>{if(!store.state.clips.length)return toast('Add a video before exporting.',true);$('#export-dialog').showModal()};$('#export-cancel').onclick=()=>exporter.cancel();$('#export-start').onclick=async()=>{const start=$('#export-start'),status=$('#export-status');start.disabled=true;status.hidden=false;try{const blob=await exporter.render({resolution:$('#export-resolution').value,quality:$('#export-quality').value,onProgress:p=>{$('#export-progress').value=p;$('#export-message').textContent=`Rendering… ${Math.round(p*100)}%`}});download(blob,'python-movie-maker-export.webm');$('#export-message').textContent='Done! Your download has started.';toast('Movie exported successfully.')}catch(e){if(e.name!=='AbortError')toast(e.message||'Export failed.',true);$('#export-message').textContent=e.name==='AbortError'?'Export cancelled.':'Export failed.'}finally{start.disabled=false}};
$('#export-start').onclick=async()=>{const start=$('#export-start'),status=$('#export-status'),format=$('#export-format').value;start.disabled=true;status.hidden=false;try{const blob=await exporter.render({resolution:$('#export-resolution').value,quality:$('#export-quality').value,format,onProgress:p=>{$('#export-progress').value=p;$('#export-message').textContent=`Rendering ${Math.round(p*100)}%`}});download(blob,`my-movie-maker-export.${format}`);$('#export-message').textContent='Done! Your download has started.';toast('Movie exported successfully.')}catch(e){if(e.name!=='AbortError')toast(e.message||'Export failed.',true);$('#export-message').textContent=e.name==='AbortError'?'Export cancelled.':'Export failed.'}finally{start.disabled=false}};
updateButtons();
