import { timelineAt } from './project.js';
export class BrowserExporter{
  constructor(store,library){this.store=store;this.library=library;this.cancelled=false}
  cancel(){this.cancelled=true}
  async render({resolution='original',quality='normal',format='mp4',onProgress=()=>{}}){
    if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw new Error('This browser cannot export video. Use a recent Chrome or Edge release.');
    const s=this.store.state,duration=this.store.duration;if(!duration)throw new Error('Add at least one video clip before exporting.');for(const c of s.clips)if(!this.library.get(c.assetId))throw new Error(`Reconnect “${c.name}” before exporting.`);
    this.cancelled=false;const first=this.library.get(s.clips[0].assetId),target=resolution==='720'?720:1080,ratio=(first.width||1920)/(first.height||1080);let h=resolution==='original'?Math.min(first.height||1080,1080):target,w=Math.round(h*ratio);w-=w%2;h-=h%2;
    const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(30);const audioCtx=new AudioContext(),dest=audioCtx.createMediaStreamDestination();const video=document.createElement('video'),music=document.createElement('audio');video.volume=0;music.volume=0;const vsrc=audioCtx.createMediaElementSource(video),msrc=audioCtx.createMediaElementSource(music),vg=audioCtx.createGain(),mg=audioCtx.createGain();vg.gain.value=s.videoMuted?0:s.videoVolume;mg.gain.value=s.musicMuted?0:s.musicVolume;vsrc.connect(vg).connect(dest);msrc.connect(mg).connect(dest);for(const t of dest.stream.getAudioTracks())stream.addTrack(t);
    const mp4Types=['video/mp4;codecs="avc1.42E01E,mp4a.40.2"','video/mp4;codecs="avc1.42E01E"','video/mp4'],webmTypes=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'],mime=(format==='mp4'?mp4Types:webmTypes).find(x=>MediaRecorder.isTypeSupported(x));if(!mime)throw new Error(format==='mp4'?'This browser cannot encode MP4 locally. Update Chrome/Edge or choose WebM.':'No supported WebM encoder was found.');const bits=quality==='high'?12_000_000:7_000_000,rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:bits}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const stopped=new Promise((ok,bad)=>{rec.onstop=ok;rec.onerror=()=>bad(new Error('The browser encoder stopped unexpectedly.'))});rec.start(1000);await audioCtx.resume();
    const started=performance.now();let lastClip='';while(!this.cancelled){const t=(performance.now()-started)/1000;if(t>=duration)break;const hit=timelineAt(s,t);if(!hit)break;const asset=this.library.get(hit.clip.assetId);if(lastClip!==hit.clip.id){video.src=asset.url;await new Promise((ok,bad)=>{video.onloadeddata=ok;video.onerror=bad});video.currentTime=hit.local;video.playbackRate=hit.clip.speed||1;await video.play();lastClip=hit.clip.id}if(Math.abs(video.currentTime-hit.local)>.3)video.currentTime=hit.local;if(s.audio){const a=this.library.get(s.audio.assetId),local=s.audio.in+t-s.audio.start;if(a&&local>=s.audio.in&&local<s.audio.out){if(music.src!==a.url){music.src=a.url;music.currentTime=local;await music.play()}else if(music.paused)await music.play()}else music.pause()}ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);const rotation=hit.clip.rotation||0;ctx.save();ctx.translate(w/2,h/2);ctx.rotate(rotation*Math.PI/180);const swap=Math.abs(rotation%180)===90,sourceW=video.videoWidth||w,sourceH=video.videoHeight||h,fit=Math.min(w/(swap?sourceH:sourceW),h/(swap?sourceW:sourceH)),dw=sourceW*fit,dh=sourceH*fit;ctx.drawImage(video,-dw/2,-dh/2,dw,dh);ctx.restore();onProgress(t/duration);await new Promise(r=>requestAnimationFrame(r))}
    video.pause();music.pause();rec.stop();await stopped;await audioCtx.close();if(this.cancelled)throw new DOMException('Export cancelled','AbortError');onProgress(1);return new Blob(chunks,{type:mime});
  }
}
