import { timelineAt, ProjectStore } from './project.js';
export class PreviewController extends EventTarget{
  constructor(video,audio,store,library){super();this.video=video;this.audio=audio;this.store=store;this.library=library;this.time=0;this.playing=false;this.last=0;this.raf=0;video.addEventListener('ended',()=>this.advance());}
  syncVolumes(){const s=this.store.state;this.video.volume=s.videoVolume;this.video.muted=s.videoMuted;this.audio.volume=s.musicVolume;this.audio.muted=s.musicMuted}
  seek(time,autoplay=this.playing){this.time=Math.max(0,Math.min(time,this.store.duration));const hit=timelineAt(this.store.state,this.time);if(!hit){this.video.removeAttribute('src');this.emit();return}const blank=document.querySelector('#blank-preview');if(hit.clip.kind==='blank'){this.video.pause();this.video.style.display='none';blank.style.display='block';blank.style.background=hit.clip.background||'#111827';this.currentId=hit.clip.id;this.syncMusic();this.emit();return}const asset=this.library.get(hit.clip.assetId);if(!asset){this.pause();this.emit();return}blank.style.display='none';this.video.style.display='block';if(this.video.src!==asset.url)this.video.src=asset.url;this.video.currentTime=hit.local;this.video.playbackRate=hit.clip.speed||1;const rotation=hit.clip.rotation||0,box=this.video.parentElement,cw=Math.max(1,box.clientWidth-8),ch=Math.max(1,box.clientHeight-8),sw=asset.width||cw,sh=asset.height||ch,rotated=Math.abs(rotation%180)===90,scale=Math.min(cw/(rotated?sh:sw),ch/(rotated?sw:sh));this.video.style.width=`${Math.floor(sw*scale)}px`;this.video.style.height=`${Math.floor(sh*scale)}px`;this.video.style.transformOrigin='center center';this.video.style.transform=`rotate(${rotation}deg)`;this.currentId=hit.clip.id;this.syncMusic();if(autoplay)this.video.play().catch(()=>this.pause());this.emit()}
  play(){if(!this.store.state.clips.length)return;if(this.time>=this.store.duration-.01)this.time=0;this.playing=true;this.seek(this.time,true);this.last=performance.now();this.tick();}
  pause(){this.playing=false;this.video.pause();this.audio.pause();cancelAnimationFrame(this.raf);this.emit()}
  toggle(){this.playing?this.pause():this.play()}
  tick=()=>{if(!this.playing)return;const now=performance.now();this.time=Math.min(this.store.duration,this.time+(now-this.last)/1000);this.last=now;const hit=timelineAt(this.store.state,this.time);if(!hit||this.time>=this.store.duration){this.pause();this.time=this.store.duration;this.emit();return}if(hit.clip.id!==this.currentId)this.seek(this.time,true);this.syncMusic();this.emit();this.raf=requestAnimationFrame(this.tick)}
  advance(){if(this.playing)this.seek(this.time,true)}
  syncMusic(){const tracks=this.store.state.audioTracks||(this.store.state.audio?[this.store.state.audio]:[]),a=[...tracks].reverse().find(track=>{const local=track.in+this.time-track.start;return local>=track.in&&local<track.out});if(!a){this.audio.pause();return}const asset=this.library.get(a.assetId),local=a.in+this.time-a.start;if(!asset){this.audio.pause();return}if(this.audio.src!==asset.url)this.audio.src=asset.url;if(Math.abs(this.audio.currentTime-local)>.25)this.audio.currentTime=local;this.syncVolumes();if(this.playing&&this.audio.paused)this.audio.play().catch(()=>{});}
  emit(){this.dispatchEvent(new CustomEvent('time',{detail:this.time}))}
}
