import { formatTime, clamp } from './utils.js';
const SCALE=48,MIN_WIDTH=34;
export class TimelineView{
  constructor(elements,store,handlers){Object.assign(this,elements);this.store=store;this.handlers=handlers;this.selected=null;this.time=0;this.bind()}
  bind(){const seek=e=>{const r=this.videoTrack.getBoundingClientRect();this.handlers.seek(clamp((e.clientX-r.left)/SCALE,0,this.store.duration))};this.timeline.addEventListener('pointerdown',e=>{if(e.target.closest('.clip'))return;seek(e);this.timeline.setPointerCapture?.(e.pointerId);const move=x=>{if(x.buttons)seek(x)};this.timeline.addEventListener('pointermove',move);this.timeline.addEventListener('pointerup',()=>this.timeline.removeEventListener('pointermove',move),{once:true})})}
  render(){const s=this.store.state,d=this.store.duration,width=Math.max(700,d*SCALE);this.timeline.style.width=`${width+78}px`;this.videoTrack.style.width=this.audioTrack.style.width=this.ruler.style.width=`${width}px`;this.videoTrack.replaceChildren();let x=0;s.clips.forEach((c,i)=>{const len=(c.out-c.in)/(c.speed||1),el=document.createElement('div');el.className=`clip${this.selected===c.id?' selected':''}`;el.style.left=`${x*SCALE}px`;el.style.width=`${Math.max(MIN_WIDTH,len*SCALE)}px`;el.draggable=true;el.dataset.id=c.id;el.innerHTML=`<div class="trim-handle trim-start" data-edge="start"></div><div class="clip-name"></div><div class="clip-time">${formatTime(len)}${(c.speed||1)!==1?` · ${c.speed}×`:''}${c.rotation?` · ${c.rotation}°`:''}</div><div class="trim-handle trim-end" data-edge="end"></div>`;el.querySelector('.clip-name').textContent=c.name;el.onclick=e=>{e.stopPropagation();this.selected=c.id;this.handlers.select(c.id);this.render()};el.ondragstart=()=>{el.classList.add('dragging');this.dragIndex=i};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();this.handlers.reorder(this.dragIndex,i)};for(const h of el.querySelectorAll('.trim-handle'))this.bindTrim(h,c,len);this.videoTrack.append(el);x+=len});this.renderAudio(width);this.renderRuler(d);this.setTime(this.time)}
  bindTrim(handle,clip,len){handle.onpointerdown=e=>{e.stopPropagation();e.preventDefault();const startX=e.clientX,edge=handle.dataset.edge,origin=edge==='start'?clip.in:clip.out,speed=clip.speed||1;const move=ev=>{const delta=(ev.clientX-startX)/SCALE*speed;const next=edge==='start'?clamp(origin+delta,0,clip.out-.1):Math.max(clip.in+.1,origin+delta);handle.parentElement.querySelector('.clip-time').textContent=formatTime((edge==='start'?clip.out-next:next-clip.in)/speed)};const up=ev=>{window.removeEventListener('pointermove',move);const delta=(ev.clientX-startX)/SCALE*speed;this.handlers.trim(clip.id,edge,origin+delta)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})}}
  renderAudio(){this.audioTrack.replaceChildren();const a=this.store.state.audio;if(!a)return;const el=document.createElement('div');el.className='clip audio-clip selected';el.style.left=`${a.start*SCALE}px`;el.style.width=`${Math.max(MIN_WIDTH,(a.out-a.in)*SCALE)}px`;el.innerHTML='<div class="wave"></div><div class="trim-handle trim-start" data-edge="start"></div><div class="clip-name"></div><div class="clip-time"></div><div class="trim-handle trim-end" data-edge="end"></div>';el.querySelector('.clip-name').textContent=a.name;el.querySelector('.clip-time').textContent=formatTime(a.out-a.in);let origin,start;el.onpointerdown=e=>{if(e.target.closest('.trim-handle'))return;origin=e.clientX;start=a.start;const move=ev=>el.style.left=`${Math.max(0,(start+(ev.clientX-origin)/SCALE)*SCALE)}px`;const up=ev=>{window.removeEventListener('pointermove',move);this.handlers.audioStart(Math.max(0,start+(ev.clientX-origin)/SCALE))};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})};for(const handle of el.querySelectorAll('.trim-handle'))handle.onpointerdown=e=>{e.stopPropagation();const edge=handle.dataset.edge,x=e.clientX,original=edge==='start'?a.in:a.out;const move=ev=>{const next=edge==='start'?clamp(original+(ev.clientX-x)/SCALE,0,a.out-.1):clamp(original+(ev.clientX-x)/SCALE,a.in+.1,a.sourceDuration);el.querySelector('.clip-time').textContent=formatTime(edge==='start'?a.out-next:next-a.in)};const up=ev=>{window.removeEventListener('pointermove',move);const raw=original+(ev.clientX-x)/SCALE;this.handlers.audioTrim(edge,edge==='start'?clamp(raw,0,a.out-.1):clamp(raw,a.in+.1,a.sourceDuration))};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})};this.audioTrack.append(el)}
  renderRuler(duration){this.ruler.replaceChildren();const step=duration>180?30:duration>60?10:5;for(let t=0;t<=Math.max(duration,15);t+=step){const m=document.createElement('span');m.className='ruler-mark';m.style.left=`${t*SCALE}px`;m.textContent=formatTime(t);this.ruler.append(m)}}
  setTime(t){this.time=t;this.playhead.style.left=`${t*SCALE}px`}
}
